In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
%matplotlib inline

pd.set_option('display.max_rows', None) #Allows for cell to contain maximum number of columns and rows. 
pd.set_option ('display.max_columns', None)

In [2]:
df = pd.read_csv(r"/Users/arthurk.richards/Downloads/WA_Fn-UseC_-Telco-Customer-Churn.csv")


df.columns = df.columns.str.lower().str.replace(' ','_')

categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)

for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(' ','_')

In [3]:
df.head().T

0             1               2  \
customerid              7590-vhveg    5575-gnvde      3668-qpybk   
gender                      female          male            male   
seniorcitizen                    0             0               0   
partner                        yes            no              no   
dependents                      no            no              no   
tenure                           1            34               2   
phoneservice                    no           yes             yes   
multiplelines     no_phone_service            no              no   
internetservice                dsl           dsl             dsl   
onlinesecurity                  no           yes             yes   
onlinebackup                   yes            no             yes   
deviceprotection                no           yes              no   
techsupport                     no            no              no   
streamingtv                     no            no              no   
streamingmovies                 no            no              no   
contract            month-to-month      one_year  month-to-month   
paperlessbilling               yes            no             yes   
paymentmethod     electronic_check  mailed_check    mailed_check   
monthlycharges               29.85         56.95           53.85   
totalcharges                 29.85        1889.5          108.15   
churn                           no            no             yes   

                                          3                 4  
customerid                       7795-cfocw        9237-hqitu  
gender                                 male            female  
seniorcitizen                             0                 0  
partner                                  no                no  
dependents                               no                no  
tenure                                   45                 2  
phoneservice                             no               yes  
multiplelines              no_phone_service                no  
internetservice                         dsl       fiber_optic  
onlinesecurity                          yes                no  
onlinebackup                             no                no  
deviceprotection                        yes                no  
techsupport                             yes                no  
streamingtv                              no                no  
streamingmovies                          no                no  
contract                           one_year    month-to-month  
paperlessbilling                         no               yes  
paymentmethod     bank_transfer_(automatic)  electronic_check  
monthlycharges                         42.3              70.7  
totalcharges                        1840.75            151.65  
churn                                    no               yes

In [4]:
df.dtypes

customerid           object
gender               object
seniorcitizen         int64
partner              object
dependents           object
tenure                int64
phoneservice         object
multiplelines        object
internetservice      object
onlinesecurity       object
onlinebackup         object
deviceprotection     object
techsupport          object
streamingtv          object
streamingmovies      object
contract             object
paperlessbilling     object
paymentmethod        object
monthlycharges      float64
totalcharges         object
churn                object
dtype: object

In [5]:
tc=pd.to_numeric(df.totalcharges, errors='coerce')

In [6]:
df[tc.isnull()][['totalcharges']]

totalcharges
488             _
753             _
936             _
1082            _
1340            _
3331            _
3826            _
4380            _
5218            _
6670            _
6754            _

In [7]:
df.totalcharges = pd.to_numeric(df.totalcharges, errors='coerce')

In [8]:
df.dtypes

customerid           object
gender               object
seniorcitizen         int64
partner              object
dependents           object
tenure                int64
phoneservice         object
multiplelines        object
internetservice      object
onlinesecurity       object
onlinebackup         object
deviceprotection     object
techsupport          object
streamingtv          object
streamingmovies      object
contract             object
paperlessbilling     object
paymentmethod        object
monthlycharges      float64
totalcharges        float64
churn                object
dtype: object

In [9]:
df.totalcharges = df.totalcharges.fillna(0)

In [10]:
df.churn.head()

0     no
1     no
2    yes
3     no
4    yes
Name: churn, dtype: object

In [11]:
df.churn=(df.churn == 'yes').astype(int)

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
df_full_train, df_test =train_test_split(df,test_size=0.2,random_state=1)

In [14]:
len(df_full_train), len(df_test)

(5634, 1409)

In [15]:
#In order to make sure we have the appropriate numbers, we now calculate how much 20% (the val_test) is of 80% (full train) which gives us 1/4 or 25%

In [16]:
df_train, df_val = train_test_split(df_full_train,test_size=0.25,random_state=1)

In [17]:
len(df_train),len(df_val),len(df_test)

(4225, 1409, 1409)

In [18]:
df_train=df_train.reset_index(drop=True)
df_val=df_val.reset_index(drop=True)
df_test=df_test.reset_index(drop=True)

In [19]:
y_train = df_train.churn.values
y_val= df_val.churn.values
y_test=df_test.churn.values

In [20]:
del df_train['churn']
del df_val['churn']


In [21]:
df_full_train = df_full_train.reset_index(drop=True)

In [22]:
df_full_train.head()

customerid  gender  seniorcitizen partner dependents  tenure phoneservice  \
0  5442-pptjy    male              0     yes        yes      12          yes   
1  6261-rcvns  female              0      no         no      42          yes   
2  2176-osjuv    male              0     yes         no      71          yes   
3  6161-erdgd    male              0     yes        yes      71          yes   
4  2364-ufrom    male              0      no         no      30          yes   

  multiplelines internetservice       onlinesecurity         onlinebackup  \
0            no              no  no_internet_service  no_internet_service   
1            no             dsl                  yes                  yes   
2           yes             dsl                  yes                  yes   
3           yes             dsl                  yes                   no   
4            no             dsl                  yes                  yes   

      deviceprotection          techsupport          streamingtv  \
0  no_internet_service  no_internet_service  no_internet_service   
1                  yes                  yes                   no   
2                   no                  yes                   no   
3                  yes                  yes                  yes   
4                   no                  yes                  yes   

       streamingmovies  contract paperlessbilling              paymentmethod  \
0  no_internet_service  two_year               no               mailed_check   
1                  yes  one_year               no    credit_card_(automatic)   
2                   no  two_year               no  bank_transfer_(automatic)   
3                  yes  one_year               no           electronic_check   
4                   no  one_year               no           electronic_check   

   monthlycharges  totalcharges  churn  
0           19.70        258.35      0  
1           73.90       3160.55      1  
2           65.15       4681.75      0  
3           85.45       6300.85      0  
4           70.40       2044.75      0

In [23]:
df_full_train.isnull().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64

In [24]:
df_full_train.churn.value_counts(normalize=True)

0    0.730032
1    0.269968
Name: churn, dtype: float64

In [25]:
#26% churn rate

In [26]:
global_churn_rate =df_full_train.churn.mean()

In [27]:
df_full_train.columns

Index(['customerid', 'gender', 'seniorcitizen', 'partner', 'dependents',
       'tenure', 'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod', 'monthlycharges', 'totalcharges', 'churn'],
      dtype='object')

In [28]:
numerical = ['tenure','monthlycharges','totalcharges']

In [29]:
categorical = ['gender', 'seniorcitizen', 'partner', 'dependents',
        'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod']

In [30]:
df_full_train[categorical].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

In [31]:
df_full_train.head()

customerid  gender  seniorcitizen partner dependents  tenure phoneservice  \
0  5442-pptjy    male              0     yes        yes      12          yes   
1  6261-rcvns  female              0      no         no      42          yes   
2  2176-osjuv    male              0     yes         no      71          yes   
3  6161-erdgd    male              0     yes        yes      71          yes   
4  2364-ufrom    male              0      no         no      30          yes   

  multiplelines internetservice       onlinesecurity         onlinebackup  \
0            no              no  no_internet_service  no_internet_service   
1            no             dsl                  yes                  yes   
2           yes             dsl                  yes                  yes   
3           yes             dsl                  yes                   no   
4            no             dsl                  yes                  yes   

      deviceprotection          techsupport          streamingtv  \
0  no_internet_service  no_internet_service  no_internet_service   
1                  yes                  yes                   no   
2                   no                  yes                   no   
3                  yes                  yes                  yes   
4                   no                  yes                  yes   

       streamingmovies  contract paperlessbilling              paymentmethod  \
0  no_internet_service  two_year               no               mailed_check   
1                  yes  one_year               no    credit_card_(automatic)   
2                   no  two_year               no  bank_transfer_(automatic)   
3                  yes  one_year               no           electronic_check   
4                   no  one_year               no           electronic_check   

   monthlycharges  totalcharges  churn  
0           19.70        258.35      0  
1           73.90       3160.55      1  
2           65.15       4681.75      0  
3           85.45       6300.85      0  
4           70.40       2044.75      0

In [32]:
df_full_train[df_full_train.gender == 'female'].churn.mean()

0.27682403433476394

In [33]:
df_full_train[df_full_train.gender == 'male'].churn.mean()

0.2632135306553911

In [34]:
churn_w_partner=df_full_train[df_full_train.partner == 'yes'].churn.mean()

In [35]:
churn_wo_partner=df_full_train[df_full_train.partner == 'no'].churn.mean()

In [36]:
global_churn_rate - churn_w_partner

0.06493474245795922

In [37]:
global_churn_rate - churn_wo_partner

-0.05984095297455855

In [38]:
#Right now I am determining feature importance, some of these insights can even immediately be shared with marketing teams if deadlines are short.

In [39]:
churn_w_partner/global_churn_rate # 25% lower Churn rate

0.7594724924338315

In [40]:
churn_wo_partner/global_churn_rate #22% higher churn rate

1.2216593879412643

In [41]:
from IPython.display import display

In [42]:
for c in categorical:

    df_group = df_full_train.groupby(c).churn.agg(['mean','count'])
    df_group['diff'] = df_group['mean'] - global_churn_rate
    df_group['risk'] = df_group['mean'] / global_churn_rate
    display(df_group)
    print()
    print()

mean  count      diff      risk
gender                                     
female  0.276824   2796  0.006856  1.025396
male    0.263214   2838 -0.006755  0.974980

mean  count      diff      risk
seniorcitizen                                     
0              0.242270   4722 -0.027698  0.897403
1              0.413377    912  0.143409  1.531208

mean  count      diff      risk
partner                                     
no       0.329809   2932  0.059841  1.221659
yes      0.205033   2702 -0.064935  0.759472

mean  count      diff      risk
dependents                                     
no          0.313760   3968  0.043792  1.162212
yes         0.165666   1666 -0.104302  0.613651

mean  count      diff      risk
phoneservice                                     
no            0.241316    547 -0.028652  0.893870
yes           0.273049   5087  0.003081  1.011412

mean  count      diff      risk
multiplelines                                        
no                0.257407   2700 -0.012561  0.953474
no_phone_service  0.241316    547 -0.028652  0.893870
yes               0.290742   2387  0.020773  1.076948

mean  count      diff      risk
internetservice                                     
dsl              0.192347   1934 -0.077621  0.712482
fiber_optic      0.425171   2479  0.155203  1.574895
no               0.077805   1221 -0.192163  0.288201

mean  count      diff      risk
onlinesecurity                                          
no                   0.420921   2801  0.150953  1.559152
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.153226   1612 -0.116742  0.567570

mean  count      diff      risk
onlinebackup                                            
no                   0.404323   2498  0.134355  1.497672
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.217232   1915 -0.052736  0.804660

mean  count      diff      risk
deviceprotection                                        
no                   0.395875   2473  0.125907  1.466379
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.230412   1940 -0.039556  0.853480

mean  count      diff      risk
techsupport                                             
no                   0.418914   2781  0.148946  1.551717
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.159926   1632 -0.110042  0.592390

mean  count      diff      risk
streamingtv                                             
no                   0.342832   2246  0.072864  1.269897
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.302723   2167  0.032755  1.121328

mean  count      diff      risk
streamingmovies                                         
no                   0.338906   2213  0.068938  1.255358
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.307273   2200  0.037305  1.138182

mean  count      diff      risk
contract                                           
month-to-month  0.431701   3104  0.161733  1.599082
one_year        0.120573   1186 -0.149395  0.446621
two_year        0.028274   1344 -0.241694  0.104730

mean  count      diff      risk
paperlessbilling                                     
no                0.172071   2313 -0.097897  0.637375
yes               0.338151   3321  0.068183  1.252560

mean  count      diff      risk
paymentmethod                                                 
bank_transfer_(automatic)  0.168171   1219 -0.101797  0.622928
credit_card_(automatic)    0.164339   1217 -0.105630  0.608733
electronic_check           0.455890   1893  0.185922  1.688682
mailed_check               0.193870   1305 -0.076098  0.718121

This allows us to look at the entirety of the dataframe and determine which features we want to utilize. A practice like this would be beneficial for a bank, marketing company or others when determining the features to utilize in a machine learning project or even in general when uncovering insights to share with stakeholders. 

In [43]:
from sklearn.metrics import mutual_info_score

In [44]:
mutual_info_score(df_full_train.churn,df_full_train.contract)

0.0983203874041556

In [45]:
mutual_info_score(df_full_train.churn,df_full_train.gender)

0.0001174846211139946

In [46]:
def mutual_info_churn_score(x):
    return mutual_info_score(df_full_train.churn,x)

In [47]:
df_full_train[categorical].apply(mutual_info_churn_score).sort_values()

gender              0.000117
phoneservice        0.000229
multiplelines       0.000857
seniorcitizen       0.009410
partner             0.009968
dependents          0.012346
paperlessbilling    0.017589
streamingmovies     0.031581
streamingtv         0.031853
paymentmethod       0.043210
deviceprotection    0.043453
onlinebackup        0.046923
internetservice     0.055868
techsupport         0.061032
onlinesecurity      0.063085
contract            0.098320
dtype: float64

In [48]:
df_full_train[numerical].corrwith(df_full_train.churn)

tenure           -0.351885
monthlycharges    0.196805
totalcharges     -0.196353
dtype: float64

In [49]:
df_full_train[df_full_train.tenure < 2].churn.mean()

0.6247464503042597

In [50]:
df_full_train[df_full_train.tenure > 2].churn.mean()

0.22478269658378816

In [51]:
df_full_train[(df_full_train.tenure > 2) & (df_full_train.tenure < 12)].churn.mean()

0.4059003051881994

In [52]:
df_full_train[df_full_train.monthlycharges < 20].churn.mean()

0.08829568788501027

In [53]:
df_full_train[df_full_train.monthlycharges > 50].churn.mean()

0.32499341585462205

In [54]:
df_full_train[(df_full_train.monthlycharges > 20) & (df_full_train.monthlycharges < 50)].churn.mean()

0.1836890243902439

In [55]:
from sklearn.feature_extraction import DictVectorizer

In [56]:
df_train[['gender','contract','tenure']].iloc[:20]

gender        contract  tenure
0   female        two_year      72
1     male  month-to-month      10
2   female  month-to-month       5
3   female  month-to-month       5
4   female        two_year      18
5     male  month-to-month       4
6     male  month-to-month       1
7   female  month-to-month       1
8   female        two_year      72
9   female  month-to-month       6
10  female        two_year      72
11    male  month-to-month      17
12  female        two_year      66
13  female  month-to-month       2
14  female  month-to-month       4
15    male  month-to-month       3
16  female        two_year      71
17  female  month-to-month      32
18    male        one_year      53
19    male        two_year      56

In [57]:
combined_columns = categorical + numerical
print(combined_columns)


['gender', 'seniorcitizen', 'partner', 'dependents', 'phoneservice', 'multiplelines', 'internetservice', 'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport', 'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling', 'paymentmethod', 'tenure', 'monthlycharges', 'totalcharges']


In [58]:
train_dicts=df_train[categorical + numerical].to_dict(orient='records')

In [59]:
train_dicts[0]

{'gender': 'female',
 'seniorcitizen': 0,
 'partner': 'yes',
 'dependents': 'yes',
 'phoneservice': 'yes',
 'multiplelines': 'yes',
 'internetservice': 'fiber_optic',
 'onlinesecurity': 'yes',
 'onlinebackup': 'yes',
 'deviceprotection': 'yes',
 'techsupport': 'yes',
 'streamingtv': 'yes',
 'streamingmovies': 'yes',
 'contract': 'two_year',
 'paperlessbilling': 'yes',
 'paymentmethod': 'electronic_check',
 'tenure': 72,
 'monthlycharges': 115.5,
 'totalcharges': 8425.15}

In [60]:
dv=DictVectorizer(sparse=False)

In [61]:
dv.fit(train_dicts)

DictVectorizer(sparse=False)

In [62]:
dv.get_feature_names_out()

array(['contract=month-to-month', 'contract=one_year',
       'contract=two_year', 'dependents=no', 'dependents=yes',
       'deviceprotection=no', 'deviceprotection=no_internet_service',
       'deviceprotection=yes', 'gender=female', 'gender=male',
       'internetservice=dsl', 'internetservice=fiber_optic',
       'internetservice=no', 'monthlycharges', 'multiplelines=no',
       'multiplelines=no_phone_service', 'multiplelines=yes',
       'onlinebackup=no', 'onlinebackup=no_internet_service',
       'onlinebackup=yes', 'onlinesecurity=no',
       'onlinesecurity=no_internet_service', 'onlinesecurity=yes',
       'paperlessbilling=no', 'paperlessbilling=yes', 'partner=no',
       'partner=yes', 'paymentmethod=bank_transfer_(automatic)',
       'paymentmethod=credit_card_(automatic)',
       'paymentmethod=electronic_check', 'paymentmethod=mailed_check',
       'phoneservice=no', 'phoneservice=yes', 'seniorcitizen',
       'streamingmovies=no', 'streamingmovies=no_internet_service',

In [63]:
dv.transform(train_dicts[:5])[0]

array([0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00, 1.00000e+00,
       0.00000e+00, 0.00000e+00, 1.00000e+00, 1.00000e+00, 0.00000e+00,
       0.00000e+00, 1.00000e+00, 0.00000e+00, 1.15500e+02, 0.00000e+00,
       0.00000e+00, 1.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00,
       0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00, 1.00000e+00,
       0.00000e+00, 1.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00,
       0.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 1.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00,
       0.00000e+00, 0.00000e+00, 1.00000e+00, 7.20000e+01, 8.42515e+03])

In [64]:
X_train = dv.fit_transform(train_dicts)

In [65]:
X_train.shape

(4225, 45)

In [66]:
val_dicts=df_val[categorical + numerical].to_dict(orient='records')

In [67]:
X_val = dv.fit_transform(val_dicts)

In [68]:
#We are ctreaing feature matrix, and so now we need to train the model 

In [69]:
#Training Logistic Regression

In [70]:
from sklearn.linear_model import LogisticRegression

In [71]:
len(y_train)

4225

In [72]:
model = LogisticRegression()
model.fit(X_train,y_train)


LogisticRegression()

In [73]:
model.coef_[0].round(3)

array([ 0.475, -0.175, -0.408, -0.03 , -0.078,  0.063, -0.089, -0.081,
       -0.034, -0.073, -0.335,  0.316, -0.089,  0.004, -0.258,  0.141,
        0.009,  0.063, -0.089, -0.081,  0.266, -0.089, -0.284, -0.231,
        0.124, -0.166,  0.058, -0.087, -0.032,  0.07 , -0.059,  0.141,
       -0.249,  0.215, -0.12 , -0.089,  0.102, -0.071, -0.089,  0.052,
        0.213, -0.089, -0.232, -0.07 ,  0.   ])

In [74]:
model.predict_proba(X_train) #the second column is the probability of churning, we can take just the second column

array([[0.90451862, 0.09548138],
       [0.32066191, 0.67933809],
       [0.36631259, 0.63368741],
       ...,
       [0.46835616, 0.53164384],
       [0.95745698, 0.04254302],
       [0.3012646 , 0.6987354 ]])

In [75]:
model.predict_proba(X_train)[:,1] #the second column is the probability of churning, we can take just the second column

array([0.09548138, 0.67933809, 0.63368741, ..., 0.53164384, 0.04254302,
       0.6987354 ])

In [76]:
y_pred=model.predict_proba(X_val)[:,1]

In [77]:
y_pred >= 0.5

array([False, False, False, ..., False,  True,  True])

In [78]:
churn_decision=(y_pred >= 0.5)

In [79]:
df_val[churn_decision].head()

customerid  gender  seniorcitizen partner dependents  tenure phoneservice  \
3   8433-wxgna    male              0      no         no       2          yes   
8   3440-jpscl  female              0      no         no       6          yes   
11  2637-fkfsy  female              0     yes         no       3          yes   
12  7228-omtpn    male              0      no         no       4          yes   
19  6711-fldfb  female              0      no         no       7          yes   

   multiplelines internetservice onlinesecurity onlinebackup deviceprotection  \
3             no     fiber_optic            yes           no               no   
8             no     fiber_optic             no           no              yes   
11            no             dsl             no           no               no   
12            no     fiber_optic             no           no               no   
19           yes     fiber_optic             no           no               no   

   techsupport streamingtv streamingmovies        contract paperlessbilling  \
3           no          no              no  month-to-month              yes   
8          yes         yes             yes  month-to-month              yes   
11          no          no              no  month-to-month              yes   
12          no         yes             yes  month-to-month              yes   
19          no          no              no  month-to-month              yes   

       paymentmethod  monthlycharges  totalcharges  
3   electronic_check           75.70        189.20  
8       mailed_check           99.95        547.65  
11      mailed_check           46.10        130.15  
12  electronic_check           88.45        370.65  
19  electronic_check           74.90        541.15

In [80]:
df_val[churn_decision].customerid.head()

3     8433-wxgna
8     3440-jpscl
11    2637-fkfsy
12    7228-omtpn
19    6711-fldfb
Name: customerid, dtype: object

In [81]:
(y_val == churn_decision).mean()

0.8034066713981547

In [82]:
df_pred = pd.DataFrame()
df_pred['probability'] = y_pred
df_pred['prediction'] = churn_decision.astype(int)
df_pred['actual']= y_val

In [83]:
df_pred.head()

probability  prediction  actual
0     0.008997           0       0
1     0.204521           0       0
2     0.212219           0       0
3     0.543058           1       1
4     0.213782           0       0

In [84]:
dv.get_feature_names_out

<bound method DictVectorizer.get_feature_names_out of DictVectorizer(sparse=False)>

In [85]:
model.coef_[0].round(3)

array([ 0.475, -0.175, -0.408, -0.03 , -0.078,  0.063, -0.089, -0.081,
       -0.034, -0.073, -0.335,  0.316, -0.089,  0.004, -0.258,  0.141,
        0.009,  0.063, -0.089, -0.081,  0.266, -0.089, -0.284, -0.231,
        0.124, -0.166,  0.058, -0.087, -0.032,  0.07 , -0.059,  0.141,
       -0.249,  0.215, -0.12 , -0.089,  0.102, -0.071, -0.089,  0.052,
        0.213, -0.089, -0.232, -0.07 ,  0.   ])

In [86]:
small = ['contract','tenure','monthlycharges']

In [87]:
df_train[small].head()

contract  tenure  monthlycharges
0        two_year      72          115.50
1  month-to-month      10           95.25
2  month-to-month       5           75.55
3  month-to-month       5           80.85
4        two_year      18           20.10

In [88]:
df_train[small].iloc[:10].to_dict(orient='records')

[{'contract': 'two_year', 'tenure': 72, 'monthlycharges': 115.5},
 {'contract': 'month-to-month', 'tenure': 10, 'monthlycharges': 95.25},
 {'contract': 'month-to-month', 'tenure': 5, 'monthlycharges': 75.55},
 {'contract': 'month-to-month', 'tenure': 5, 'monthlycharges': 80.85},
 {'contract': 'two_year', 'tenure': 18, 'monthlycharges': 20.1},
 {'contract': 'month-to-month', 'tenure': 4, 'monthlycharges': 30.5},
 {'contract': 'month-to-month', 'tenure': 1, 'monthlycharges': 75.1},
 {'contract': 'month-to-month', 'tenure': 1, 'monthlycharges': 70.3},
 {'contract': 'two_year', 'tenure': 72, 'monthlycharges': 19.75},
 {'contract': 'month-to-month', 'tenure': 6, 'monthlycharges': 109.9}]

In [89]:
dicts_train_small=df_train[small].to_dict(orient='records')
dicts_val_small=df_val[small].to_dict(orient='records')

In [90]:
dv_small = DictVectorizer(sparse=False)
dv_small.fit(dicts_train_small)

DictVectorizer(sparse=False)

In [91]:
dv_small.get_feature_names_out()

array(['contract=month-to-month', 'contract=one_year',
       'contract=two_year', 'monthlycharges', 'tenure'], dtype=object)

In [92]:
X_train_small = dv_small.transform(dicts_train_small)
model_small = LogisticRegression()
model_small.fit(X_train_small,y_train)

LogisticRegression()

In [93]:
w0=model_small.intercept_[0]
w0

-2.476775664719812

In [94]:
w = model_small.coef_[0]
w.round(3)

array([ 0.97 , -0.025, -0.949,  0.027, -0.036])

In [95]:
dict(zip(dv_small.get_feature_names_out(),w.round(3)))

{'contract=month-to-month': 0.97,
 'contract=one_year': -0.025,
 'contract=two_year': -0.949,
 'monthlycharges': 0.027,
 'tenure': -0.036}

In [96]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [97]:
-2.47 + 0.97 + 60 * 0.027 +1 * (-0.036)

0.08399999999999966

#### All of this is based on the features. 2.47 is the bias #
Why are the negative features good in this regard? Meaning the negative features are 1 yr and 2 yr and they do not 

In [98]:
sigmoid(_)

0.5209876607065322

This is the churn rate

In [99]:
dicts_full_train = df_full_train[categorical + numerical].to_dict(orient='records')

In [100]:
dv = DictVectorizer(sparse=False)
X_full_train = dv.fit_transform(dicts_full_train)

In [101]:
y_full_train = df_full_train.churn.values

In [102]:
model = LogisticRegression()
model.fit(X_full_train,y_full_train)

LogisticRegression()

In [103]:
dicts_test = df_test[categorical+numerical].to_dict(orient='records')

In [104]:
X_test = dv.transform(dicts_test)

In [105]:
y_pred = model.predict_proba(X_test)[:,1]

In [106]:
churn_decision = (y_pred >= 0.5)

In [107]:
(churn_decision == y_test).mean()

0.815471965933286

In [108]:
customer=dicts_test[10]

In [109]:
X_small=dv.transform([customer])

In [110]:
model.predict_proba(X_small)[0,1]

0.4056810977887409

In [111]:
y_test[10]

0

In [112]:
customer=dicts_test[-1]

In [113]:
X_small=dv.transform([customer])

In [114]:
model.predict_proba(X_small)[0,1]

0.5968852088281937

In [115]:
y_test[-1]

1

In [116]:
val_dict = df_val[categorical+numerical].to_dict(orient='records')

In [117]:
X_val = dv.transform(val_dict)

In [118]:
y_pred = model.predict_proba(X_val)[:,1]

In [119]:
churn_decision = (y_pred >= 0.5)

In [120]:
(churn_decision == y_test).mean()

0.6486870120652946